version: '3.6'
services:
  ts3:
    image: teamspeak
    restart: always
    network_mode: host
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: 127.0.0.1
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: examplepassword
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 120
      TS3SERVER_LICENSE: accept
    volumes:
      - /opt/ts3/ts3:/var/ts3server
    depends_on:
      - ts3db
    healthcheck:
      test: ["CMD", "nc", "-zuv", "127.0.0.1" , "9987"]
      interval: 83s
      timeout: 10s
      retries: 3
      start_period: 60s
  ts3db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: teamspeak
      MARIADB_EXTRA_FLAGS: --log-warnings=1
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - /opt/ts3/ts3db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/bin/mysql" , "--user=root" , "--password=examplepassword" , "--execute" , "SHOW DATABASES;"]
      interval: 83s
      timeout: 10s
      retries: 3
      start_period: 60s
  ts3autoheal:
    image: willfarrell/autoheal
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
