version: '3.1'
services:
  ts3:
    image: teamspeak
    restart: always
    network_mode: host
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: 127.0.0.1
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: examplepassword
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - /opt/ts3/ts3:/var/ts3server
  ts3db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: teamspeak
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - /opt/ts3/ts3db:/var/lib/mysql
